name: Pulumi preview changes
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Clean install of depedencies
        run: npm ci
      - name: Change working directory for pulumi preview
        working-directory: ./infra
      - name: Run pulumi preview on dev stack
        uses: pulumi/actions@v3
        with:
          command: preview --stack dev
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_SERVER_ACCESS_SECRET_NAME: ${{ secrets.PULUMI_ACCESS_TOKEN }}
