name: Pulumi preview build
on:
  pull_request:
    branches: [master, dev]
jobs:
  preview-build:
    name: Pulumi preview build to see the the desired changes in the ifrasturcture
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean install of depedencies in root folder
        run: npm ci

      - name: Run pulumi preview on dev stack
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: ./infra # directory where the pulumi app is placed
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_SERVER_ACCESS_SECRET_NAME: ${{ secrets.AWS_SERVER_ACCESS_SECRET_NAME }}
          AWS_EXPOSED_PORT: ${{ secrets.AWS_EXPOSED_PORT}}
          AWS_REGION: ${{ secrets.AWS_REGION}}
